steps:
  ########## Fore core(frontend, backend code) ##########
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/$REPO_NAME-core-$_DEPLOY_ENV:$REVISION_ID
      - -t
      - gcr.io/$PROJECT_ID/$REPO_NAME-core-$_DEPLOY_ENV:latest
      - -f
      - cloudbuild/Dockerfile-core
      - .
      - --build-arg
      - BRANCH_NAME=$BRANCH_NAME
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/$REPO_NAME-core-$_DEPLOY_ENV:$REVISION_ID
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/$REPO_NAME-core-$_DEPLOY_ENV:latest
  - name: gcr.io/cloud-builders/gcloud
    args:
      - --project=$_CLUSTER_PROJECT
      - container
      - clusters
      - get-credentials
      - --zone=$_CLUSTER_ZONE
      - $_CLUSTER_NAME
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/absinthe-core
      - absinthe-core=gcr.io/$PROJECT_ID/$REPO_NAME-core-$_DEPLOY_ENV:$REVISION_ID
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_CLUSTER_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
      - 'CLOUDSDK_CORE_PROJECT=$_CLUSTER_PROJECT'
  - name: gcr.io/rd1-resources/auto-remove-image
    args:
      - last-image-remove
      - gcr.io/$PROJECT_ID/$REPO_NAME-core-$_DEPLOY_ENV
  ########## For nginx ##########
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/$REPO_NAME-nginx-$_DEPLOY_ENV:$REVISION_ID
      - -t
      - gcr.io/$PROJECT_ID/$REPO_NAME-nginx-$_DEPLOY_ENV:latest
      - -f
      - cloudbuild/Dockerfile-nginx
      - .
      - --build-arg
      - BRANCH_NAME=$BRANCH_NAME
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/$REPO_NAME-nginx-$_DEPLOY_ENV:$REVISION_ID
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/$REPO_NAME-nginx-$_DEPLOY_ENV:latest
  - name: gcr.io/cloud-builders/gcloud
    args:
      - --project=$_CLUSTER_PROJECT
      - container
      - clusters
      - get-credentials
      - --zone=$_CLUSTER_ZONE
      - $_CLUSTER_NAME
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/absinthe-nginx
      - absinthe-nginx=gcr.io/$PROJECT_ID/$REPO_NAME-nginx-$_DEPLOY_ENV:$REVISION_ID
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_CLUSTER_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
      - 'CLOUDSDK_CORE_PROJECT=$_CLUSTER_PROJECT'
  - name: gcr.io/rd1-resources/auto-remove-image
    args:
      - last-image-remove
      - gcr.io/$PROJECT_ID/$REPO_NAME-nginx-$_DEPLOY_ENV
