<?php
/**
 * API層
 * 一律使用 11203 + 一位類別碼 + 三位數字
 * error_msg = 基本回傳訊息
 * append_msg = 判斷是否需要串上原本的錯誤訊息
 * alert = 是否需要通知telegram
 */

return [
    //  參數或資料錯誤  112033XXX
    '112033000' => ['error_msg' => '参数输入错误', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => true, 'alert' => false],
    '112033001' => ['error_msg' => '参数错误', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => true, 'alert' => false],
    '112033002' => ['error_msg' => '资料库错误', 'custom_msg' => '资料异常，请联络客服！', 'append_msg' => true, 'alert' => false],
    '112033003' => ['error_msg' => '资料库无资料', 'custom_msg' => '资料异常，请联络客服！', 'append_msg' => true, 'alert' => false],
    '112033004' => ['error_msg' => 'API KEY无效', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => true, 'alert' => false],
    '112033005' => ['error_msg' => '背景处理异常', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => true, 'alert' => false],
    '112033006' => ['error_msg' => '请确实输入投注选项', 'custom_msg' => '请确实输入投注金额', 'append_msg' => true, 'alert' => false],

    //  內部API錯誤  11203XXXX
    // '112033000' => ['error_msg' => '参数输入错误', 'custom_msg' => '请确实输入投注金额', 'append_msg' => true, 'alert' => false],

    //  外部API錯誤  11203XXXX (後四碼與端口狀態碼相同)
    '112030000' => ['error_msg' => '端口回传资料为空', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => true, 'alert' => false],
    '112030100' => ['error_msg' => '成功', 'append_msg' => false, 'alert' => false],
    '112030101' => ['error_msg' => '无效时间戳', 'custom_msg' => '请重新登入', 'append_msg' => false, 'alert' => false],
    '112030102' => ['error_msg' => '无效令牌, 请重新登入', 'custom_msg' => '请重新登入', 'append_msg' => false, 'alert' => false],
    '112030107' => ['error_msg' => '无效开始时间', 'custom_msg' => '请选择正确日期', 'append_msg' => false, 'alert' => false],
    '112030108' => ['error_msg' => '无效结束时间', 'custom_msg' => '请选择正确日期', 'append_msg' => false, 'alert' => false],
    '112030202' => ['error_msg' => '无效用户名', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030210' => ['error_msg' => '无效商户', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030305' => ['error_msg' => '无效语言编码', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030311' => ['error_msg' => '无效时间范围', 'custom_msg' => '请选择正确日期', 'append_msg' => false, 'alert' => false],
    '112030313' => ['error_msg' => '无效体育 ID', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030330' => ['error_msg' => '无效赛事类型 ID', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030331' => ['error_msg' => '无效竞赛 ID', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030332' => ['error_msg' => '无效盘口', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030333' => ['error_msg' => '无效操作会话', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030334' => ['error_msg' => '无效赛事 ID', 'custom_msg' => '请重新整理页面', 'append_msg' => false, 'alert' => false],
    '112030335' => ['error_msg' => '无效赌注类型', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030336' => ['error_msg' => '无效投注类型 ID', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030337' => ['error_msg' => '无效赌注类型 ID', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030338' => ['error_msg' => '无效 Marketline ID', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030339' => ['error_msg' => '无效定位类型', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030340' => ['error_msg' => '无效连串过关选项', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030341' => ['error_msg' => '无效投注金额', 'custom_msg' => '无效投注金额，请重新输入投注金额', 'append_msg' => false, 'alert' => false],
    '112030342' => ['error_msg' => '无效投注类型选项 ID', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030343' => ['error_msg' => '无效优胜冠军队伍 ID', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030344' => ['error_msg' => '无效赔率类型', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030345' => ['error_msg' => '无效让球盘', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030346' => ['error_msg' => '无效赔率', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030347' => ['error_msg' => '无效主队得分', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030348' => ['error_msg' => '无效客队得分', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030349' => ['error_msg' => '无效投注状态', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030350' => ['error_msg' => '检索投注信息错误', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030351' => ['error_msg' => '无效伺服器 IP 地址', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030352' => ['error_msg' => '无效客户 MAC 地址', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030353' => ['error_msg' => '无效用户代理', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030355' => ['error_msg' => '超出赌注上限', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030356' => ['error_msg' => '无效时区', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030357' => ['error_msg' => '无效单项快速投注', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030358' => ['error_msg' => '无效连串过关快速投注', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030359' => ['error_msg' => '无效新闻 ID', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030360' => ['error_msg' => '无效投注限额组别', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030361' => ['error_msg' => '无效时段 ID', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030362' => ['error_msg' => '无效的事件组类型标识', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030363' => ['error_msg' => '事件组编号无效', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030364' => ['error_msg' => '无效价格 ID', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030365' => ['error_msg' => '无效赌注金额', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030366' => ['error_msg' => '无效派彩', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030367' => ['error_msg' => '价格ID过期', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030368' => ['error_msg' => '赌注无法出售. 上一个请求正在进行中', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030369' => ['error_msg' => '注单已售给提前兑现', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030370' => ['error_msg' => '查无注单或注单已结算', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false], //TODO 官方未列出
    '112030380' => ['error_msg' => '无可选盘口或暂时关盘', 'custom_msg' => '无可选盘口或暂时关盘, 请选择其它盘口', 'append_msg' => false, 'alert' => false],
    '112030381' => ['error_msg' => '赔率不一致', 'custom_msg' => '赔率不一致，请重新取得投注单', 'append_msg' => false, 'alert' => false],
    '112030390' => ['error_msg' => '无效 App 版本', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030391' => ['error_msg' => '无效 App 设备名称', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030392' => ['error_msg' => '无效 App 型号', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030393' => ['error_msg' => '无效 App 平台', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030394' => ['error_msg' => '无效AppOS版本', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030395' => ['error_msg' => '在地区限制投注', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030396' => ['error_msg' => '客户IP地址无效', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030397' => ['error_msg' => '无效排序', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030398' => ['error_msg' => '无效页面大小', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030399' => ['error_msg' => '无效运营商', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030400' => ['error_msg' => '系统错误', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030401' => ['error_msg' => '无效筛选', 'custom_msg' => '无效筛选，请重新输入搜寻文字', 'append_msg' => false, 'alert' => false],
    '112030402' => ['error_msg' => '页码无效', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030500' => ['error_msg' => '不授权访问', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030600' => ['error_msg' => 'Delta 过期', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112030700' => ['error_msg' => '维护', 'custom_msg' => '游戏维护中', 'append_msg' => false, 'alert' => false],
    '112030710' => ['error_msg' => '访问地区限制', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112031000' => ['error_msg' => '投注错误(没有成功投注)', 'custom_msg' => '投注失败，请重新取得赔率后再试', 'append_msg' => false, 'alert' => false],
    '112031001' => ['error_msg' => '赔率更新中', 'custom_msg' => '赔率更新中，请重新取得投注单', 'append_msg' => false, 'alert' => false],
    '112031102' => ['error_msg' => '会员用户不活跃', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112031103' => ['error_msg' => '余额不足', 'custom_msg' => '余额不足，请重新输入投注金额', 'append_msg' => false, 'alert' => false],
    '112031105' => ['error_msg' => '投注金额超于限额', 'custom_msg' => '投注金额超于下注限额', 'append_msg' => false, 'alert' => false],
    '112031106' => ['error_msg' => '投注金额低于最小投注额', 'custom_msg' => '投注金额低于最小投注额', 'append_msg' => false, 'alert' => false],
    '112031107' => ['error_msg' => '赔率已变更', 'custom_msg' => '赔率已变更，请重新取得投注单', 'append_msg' => false, 'alert' => false],
    '112031108' => ['error_msg' => '这赛事总投注金额超于限额', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112031126' => ['error_msg' => '所选赛事不支持连串过关，请选其他赛事', 'custom_msg' => '所选赛事不支持连串过关，请选其他赛事', 'append_msg' => false, 'alert' => false],
    '112031132' => ['error_msg' => '无效投注金额', 'custom_msg' => '请重新输入投注金额', 'append_msg' => false, 'alert' => false],
    '112031135' => ['error_msg' => '比赛日期验证失效', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112031136' => ['error_msg' => '赛季 ID 验证失效', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112031141' => ['error_msg' => '此项体育不存在', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112031554' => ['error_msg' => '无效注单', 'custom_msg' => '无效注单，请于两秒后再进行投注', 'append_msg' => false, 'alert' => false],
    '112031556' => ['error_msg' => '虚拟足球未启用', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112031557' => ['error_msg' => '虚拟篮球未启用', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112032102' => ['error_msg' => '快速投注金额不能低于最低投注限额', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],
    '112032103' => ['error_msg' => '快速连串过关投注金额不能低于最低投注限额', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],

    //  暫存使用   112039XXX
    '112039000' => ['error_msg' => '未知错误', 'custom_msg' => '服务异常，请联络客服！', 'append_msg' => false, 'alert' => false],

];
