<template>
  <div v-show="loading" class="loadingMask">
    <div class="loadingio-spinner-double-ring-onwhvnzijpf">
      <div class="ldio-fp47e2rd1au">
        <div></div>
        <div></div>
        <div>
          <div></div>
        </div>
        <div>
          <div></div>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
import { mapState } from "vuex";
export default {
  computed: {
    ...mapState({
      loadingArr: state => state.common.loading
    }),
    loading() {
      if (this.loadingArr.length > 0) {
        return true;
      } else return false;
    }
  }
};
</script>
<style lang="scss" scoped>
.loadingMask {
  display: -ms-flexbox;
  display: flex;
  -ms-flex-pack: center;
  justify-content: center;
  -ms-flex-align: center;
  align-items: center;

  width: 100%;
  z-index: 1002;
  text-align: center;
  position: absolute;
  background: rgba(255, 255, 255, 0.8) center center no-repeat;
  height: 100%;
}
@keyframes ldio-fp47e2rd1au {
  0% {
    transform: rotate(0);
  }
  100% {
    transform: rotate(360deg);
  }
}
.ldio-fp47e2rd1au div {
  box-sizing: border-box !important;
}
.ldio-fp47e2rd1au > div {
  position: absolute;
  width: 172.20000000000002px;
  height: 172.20000000000002px;
  top: 57.400000000000006px;
  left: 57.400000000000006px;
  border-radius: 50%;
  border: 11.48px solid #000;
  border-color: var(--primary) transparent var(--primary) transparent;
  animation: ldio-fp47e2rd1au 0.7407407407407407s linear infinite;
}

.ldio-fp47e2rd1au > div:nth-child(2),
.ldio-fp47e2rd1au > div:nth-child(4) {
  width: 143.5px;
  height: 143.5px;
  top: 71.75px;
  left: 71.75px;
  animation: ldio-fp47e2rd1au 0.7407407407407407s linear infinite reverse;
}
.ldio-fp47e2rd1au > div:nth-child(2) {
  border-color: transparent var(--secondary) transparent var(--secondary);
}
.ldio-fp47e2rd1au > div:nth-child(3) {
  border-color: transparent;
}
.ldio-fp47e2rd1au > div:nth-child(3) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-fp47e2rd1au > div:nth-child(3) div:before,
.ldio-fp47e2rd1au > div:nth-child(3) div:after {
  content: "";
  display: block;
  position: absolute;
  width: 11.48px;
  height: 11.48px;
  top: -11.48px;
  left: 68.88px;
  background: var(--primary);
  border-radius: 50%;
  box-shadow: 0 160.72px 0 0 var(--primary);
}
.ldio-fp47e2rd1au > div:nth-child(3) div:after {
  left: -11.48px;
  top: 68.88px;
  box-shadow: 160.72px 0 0 0 var(--primary);
}

.ldio-fp47e2rd1au > div:nth-child(4) {
  border-color: transparent;
}
.ldio-fp47e2rd1au > div:nth-child(4) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-fp47e2rd1au > div:nth-child(4) div:before,
.ldio-fp47e2rd1au > div:nth-child(4) div:after {
  content: "";
  display: block;
  position: absolute;
  width: 11.48px;
  height: 11.48px;
  top: -11.48px;
  left: 54.53px;
  background: var(--secondary);
  border-radius: 50%;
  box-shadow: 0 132.02px 0 0 var(--secondary);
}
.ldio-fp47e2rd1au > div:nth-child(4) div:after {
  left: -11.48px;
  top: 54.53px;
  box-shadow: 132.02px 0 0 0 var(--secondary);
}
.loadingio-spinner-double-ring-onwhvnzijpf {
  width: 287px;
  height: 287px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-fp47e2rd1au {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-fp47e2rd1au div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>